sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  #Initial setup of Google Cloud on Travis
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project propane-service-289014
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  #Login to Docker, DOCKER_PASSWORD and DOCKER_USERNAME would be provided as a environment variables through Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #Build tests of multi-client
  - docker build -t tonyvu1991/react-test -f ./client/Dockerfile.dev ./client

script:
  #Run the test container built above
  - docker run -e CI=true tonyvu1991/react-test npm test -- --coverage

deploy:
  #Custom deployment provider
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
